### ISSUE TITLE
incompatible with  sodium 0.2.0 (built from source)

### ISSUE THREAD

**Issue by ProfessorSniff** [Johni0702/fade-in-chunks#11]
![image](https://user-images.githubusercontent.com/65641177/121472146-4f7dbe80-c9b0-11eb-9166-1b20ce323ebf.png)
Using Sodium 0.2 (for [iris shaders](https://github.com/IrisShaders/Iris)) will return an error on startup.
Is Sodium 0.2 missing anything this mod needs in order to run, or is it simply failing the dependency check?

**Comment by Johni0702** [comment]
Fade In Chunks is more of a Sodium mod than a Minecraft mod. The chances of it working with a Sodium version which it was not designed for are similar to those of a normal mod working with a different Minecraft version, i.e. possible but not particularly likely.

It's pretty much guaranteed to be incompatible with Iris' fork though, because it [dynamically modifies Sodium's shader](https://github.com/Johni0702/fade-in-chunks/blob/9b24462fb4031cc17174af3bffbd36d8526c1515/src/main/java/de/johni0702/minecraft/fadeinchunks/mixin/ShaderLoaderMixin.java), which Iris presumably completely replaces.

I will probably update it to Sodium 0.2.0 once it's released. Don't know whether it's even feasible to do for Iris given it can load arbitrary shaders, and the way it works (by covering the chunk in fog) might not even work well depending on how the shader renders fog / the sky behind the chunk.

**Comment by ProfessorSniff** [comment]
thanks, this is an excellent explanation on why it won't work.

**Comment by iperrealistico** [comment]
Would definetly be cool to have fade in animation with shaders too. In the past I suggested optifine's dev to implement a variable to keep track of how long the chunk had been loaded so that shaders could implement load fog. The suggestion had been ignored lol would be cool to have something like that here
